In [1]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
---------------

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [2]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[ 5.6799e-24,  4.5682e-43,  1.2725e-20],
        [ 4.5682e-43,  1.1584e-23,  4.5682e-43],
        [ 2.4510e+28,  0.0000e+00,  2.4509e+28],
        [ 0.0000e+00,  5.6241e-24,  4.5682e-43],
        [ 5.6799e-24,  4.5682e-43,  1.2726e-20]])


Construct a randomly initialized matrix:



In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[ 0.2547,  0.8667,  0.1218],
        [ 0.6347,  0.4779,  0.4505],
        [ 0.6484,  0.3676,  0.5392],
        [ 0.6723,  0.9948,  0.1443],
        [ 0.9050,  0.4403,  0.1635]])


Construct a matrix filled zeros and of dtype long:



In [5]:
x = torch.zeros(5, 3)
print(x)

tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]])


Construct a tensor directly from data:



In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([ 5.5000,  3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x)    # override dtype!
print(x)                   # result has the same size

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[ 0.1905, -0.4524, -0.0535],
        [-1.3536,  1.0854,  0.4626],
        [-3.0122, -1.4118,  0.8946],
        [-2.0121, -1.9843,  1.2061],
        [-0.7950, -0.2371, -0.6236]], dtype=torch.float64)


Get its size:



In [8]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


Transpose a tensor:

In [9]:
y = x.t()
print(y.size())

torch.Size([3, 5])


Note that 'transposing' a tensor does not create a new tensor. The both variables now share the same memory.

In [10]:
print('y:')
print(y)

y[0] = 0.

print('y:')
print(y)

print('x:')
print(x)

y:
tensor([[ 0.1905, -1.3536, -3.0122, -2.0121, -0.7950],
        [-0.4524,  1.0854, -1.4118, -1.9843, -0.2371],
        [-0.0535,  0.4626,  0.8946,  1.2061, -0.6236]], dtype=torch.float64)
y:
tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.4524,  1.0854, -1.4118, -1.9843, -0.2371],
        [-0.0535,  0.4626,  0.8946,  1.2061, -0.6236]], dtype=torch.float64)
x:
tensor([[ 0.0000, -0.4524, -0.0535],
        [ 0.0000,  1.0854,  0.4626],
        [ 0.0000, -1.4118,  0.8946],
        [ 0.0000, -1.9843,  1.2061],
        [ 0.0000, -0.2371, -0.6236]], dtype=torch.float64)


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [11]:
x = torch.rand(5, 3) # [0-1]
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.2301,  1.9407,  0.4656],
        [ 1.8002,  0.6974,  0.5668],
        [ 1.7234,  0.7915,  1.7793],
        [ 1.1921,  0.5108,  0.6200],
        [ 0.8253,  0.5443,  0.2446]])


Addition: syntax 2



In [12]:
print(torch.add(x, y))

tensor([[ 0.2301,  1.9407,  0.4656],
        [ 1.8002,  0.6974,  0.5668],
        [ 1.7234,  0.7915,  1.7793],
        [ 1.1921,  0.5108,  0.6200],
        [ 0.8253,  0.5443,  0.2446]])


Addition: providing an output tensor as argument



In [13]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.2301,  1.9407,  0.4656],
        [ 1.8002,  0.6974,  0.5668],
        [ 1.7234,  0.7915,  1.7793],
        [ 1.1921,  0.5108,  0.6200],
        [ 0.8253,  0.5443,  0.2446]])


Addition: in-place



In [14]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.2301,  1.9407,  0.4656],
        [ 1.8002,  0.6974,  0.5668],
        [ 1.7234,  0.7915,  1.7793],
        [ 1.1921,  0.5108,  0.6200],
        [ 0.8253,  0.5443,  0.2446]])


All the other point-wise operations including 
- Subtraction
- Multiplication
- Divison

have similar syntaxes.

In [15]:
x = torch.rand(5, 3) # [0-1]
y = torch.rand(5, 3)

# subtraction
print('Subtraction')

print(x - y)
print(torch.sub(x, y))
torch.sub(x, y, out=result)
print(result)

print()

# multiplication 
print('Multiplication')

print(x * y)
print(torch.mul(x, y))
torch.mul(x, y, out=result)
print(result)

print()

# division 
print('Division')

print(x / y)
print(torch.div(x, y))
torch.div(x, y, out=result)
print(result)

print()

Subtraction
tensor([[-0.0740, -0.4093, -0.3607],
        [-0.4722,  0.6920,  0.3504],
        [-0.3212,  0.6998, -0.2162],
        [-0.1562, -0.8671, -0.0989],
        [ 0.1139, -0.1284,  0.6570]])
tensor([[-0.0740, -0.4093, -0.3607],
        [-0.4722,  0.6920,  0.3504],
        [-0.3212,  0.6998, -0.2162],
        [-0.1562, -0.8671, -0.0989],
        [ 0.1139, -0.1284,  0.6570]])
tensor([[-0.0740, -0.4093, -0.3607],
        [-0.4722,  0.6920,  0.3504],
        [-0.3212,  0.6998, -0.2162],
        [-0.1562, -0.8671, -0.0989],
        [ 0.1139, -0.1284,  0.6570]])

Multiplication
tensor([[ 0.2141,  0.1520,  0.3427],
        [ 0.4249,  0.3051,  0.6160],
        [ 0.0153,  0.1687,  0.0216],
        [ 0.8053,  0.0841,  0.8787],
        [ 0.2059,  0.1032,  0.0214]])
tensor([[ 0.2141,  0.1520,  0.3427],
        [ 0.4249,  0.3051,  0.6160],
        [ 0.0153,  0.1687,  0.0216],
        [ 0.8053,  0.0841,  0.8787],
        [ 0.2059,  0.1032,  0.0214]])
tensor([[ 0.2141,  0.1520,  0.3427],
     

Multiplying two tensors:

In [16]:
x = torch.rand(5, 3)
y = torch.rand(3, 4)

z = torch.matmul(x, y)
print(z)
print(z.size())

tensor([[ 1.7064,  1.5714,  1.1679,  1.5007],
        [ 1.4278,  1.3712,  1.0103,  1.1342],
        [ 1.3221,  1.1126,  0.9541,  1.4625],
        [ 1.3140,  1.2609,  0.8398,  0.9864],
        [ 0.9620,  0.7599,  0.7100,  1.2008]])
torch.Size([5, 4])


In [17]:
z = torch.mm(x, y)
print(z)
print(z.size())

tensor([[ 1.7064,  1.5714,  1.1679,  1.5007],
        [ 1.4278,  1.3712,  1.0103,  1.1342],
        [ 1.3221,  1.1126,  0.9541,  1.4625],
        [ 1.3140,  1.2609,  0.8398,  0.9864],
        [ 0.9620,  0.7599,  0.7100,  1.2008]])
torch.Size([5, 4])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

PyTorch tensors also support numpy like broadcasting!

In [18]:
a = torch.rand(3, 3)
b = 10

print('First tensor')
print(a)
print()

print('Tensor * Scalar')
print(a * b)
print()

First tensor
tensor([[ 0.5518,  0.9654,  0.1692],
        [ 0.7624,  0.4064,  0.1755],
        [ 0.7755,  0.9354,  0.6817]])

Tensor * Scalar
tensor([[ 5.5178,  9.6542,  1.6924],
        [ 7.6241,  4.0637,  1.7546],
        [ 7.7552,  9.3544,  6.8166]])



In [19]:
a = torch.tensor([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = torch.tensor([1.0,2.0,3.0])  
   
print('First tensor:')
print(a)
print(a.size())
print()  
   
print('Second tensor:')
print(b)
print(b.size())
print()  
   
print('First tensor + Second tensor')
print(a + b)

First tensor:
tensor([[  0.,   0.,   0.],
        [ 10.,  10.,  10.],
        [ 20.,  20.,  20.],
        [ 30.,  30.,  30.]])
torch.Size([4, 3])

Second tensor:
tensor([ 1.,  2.,  3.])
torch.Size([3])

First tensor + Second tensor
tensor([[  1.,   2.,   3.],
        [ 11.,  12.,  13.],
        [ 21.,  22.,  23.],
        [ 31.,  32.,  33.]])


In [20]:
a = torch.tensor([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = torch.tensor([[1.0],[2.0],[3.0],[4.0]])  
   
print('First tensor:')
print(a)
print(a.size())
print()  
   
print('Second tensor:')
print(b)
print(b.size())
print()  
   
print('First tensor + Second tensor')
print(a + b)

First tensor:
tensor([[  0.,   0.,   0.],
        [ 10.,  10.,  10.],
        [ 20.,  20.,  20.],
        [ 30.,  30.,  30.]])
torch.Size([4, 3])

Second tensor:
tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.]])
torch.Size([4, 1])

First tensor + Second tensor
tensor([[  1.,   1.,   1.],
        [ 12.,  12.,  12.],
        [ 23.,  23.,  23.],
        [ 34.,  34.,  34.]])


You can use standard NumPy-like indexing with all bells and whistles!

In [21]:
print(x[:, 1])

tensor([ 0.6928,  0.8911,  0.8748,  0.0739,  0.7340])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [22]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [23]:
print(x)
print(x.view(-1, 8))
print(x.view(8, -1))

tensor([[ 1.3277,  0.8324, -1.1691, -1.7008],
        [-1.9817, -1.2270,  1.1338,  0.7591],
        [-0.5319,  0.5711, -1.2077,  0.4897],
        [ 1.8525, -0.3423, -2.7757, -0.0508]])
tensor([[ 1.3277,  0.8324, -1.1691, -1.7008, -1.9817, -1.2270,  1.1338,
          0.7591],
        [-0.5319,  0.5711, -1.2077,  0.4897,  1.8525, -0.3423, -2.7757,
         -0.0508]])
tensor([[ 1.3277,  0.8324],
        [-1.1691, -1.7008],
        [-1.9817, -1.2270],
        [ 1.1338,  0.7591],
        [-0.5319,  0.5711],
        [-1.2077,  0.4897],
        [ 1.8525, -0.3423],
        [-2.7757, -0.0508]])


In [24]:
y[4] = 5.
print(x)

tensor([[ 1.3277,  0.8324, -1.1691, -1.7008],
        [ 5.0000, -1.2270,  1.1338,  0.7591],
        [-0.5319,  0.5711, -1.2077,  0.4897],
        [ 1.8525, -0.3423, -2.7757, -0.0508]])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [25]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.5406])
-0.5405568480491638


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array


In [26]:
a = torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [27]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [28]:
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically



In [29]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [30]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([ 0.4594], device='cuda:0')
tensor([ 0.4594], dtype=torch.float64)


In [31]:
x.to("cuda")

tensor([-0.5406], device='cuda:0')